// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("LandingPage");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return /* array */[
                      React.createElement("div", {
                            className: "main-splash page"
                          }, React.createElement("div", {
                                className: "main-splash-nav"
                              }, React.createElement("div", undefined, React.createElement("a", {
                                        href: "https://github.com/ncthbrt/refract"
                                      }, "Github")), React.createElement("div", undefined, React.createElement("a", {
                                        href: "https://github.com/ncthbrt/refract"
                                      }, "Reference")), React.createElement("div", undefined, React.createElement("a", {
                                        href: "https://github.com/ncthbrt/refract"
                                      }, "Guides"))), React.createElement("div", {
                                className: "main-splash-content"
                              }, React.createElement("img", {
                                    className: "main-logo ",
                                    src: "/RefractLogo.svg"
                                  }), React.createElement("h1", undefined, React.createElement("a", {
                                        href: "/"
                                      }, "REFRACT")), React.createElement("h2", undefined, "A composable web framework", React.createElement("br", undefined), "for OCaml & ReasonML"))),
                      React.createElement("div", {
                            className: "page"
                          }, React.createElement("h2", undefined, "WHY?"))
                    ];
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var R = 0;

exports.R = R;
exports.component = component;
exports.make = make;
/* component Not a pure module */
